version: "3"

services:
  rgs_server:
    build:
      context: '$PWD'
      dockerfile: '$PWD/docker/Dockerfile.rgs'
    volumes:
      - '$PWD:/usr/src/app:cached'
    links:
      - postgres
      - bitcoin-core-tbtc
    depends_on:
      - postgres
    environment:
      - RAPID_GOSSIP_SYNC_SERVER_DB_HOST=postgres
      - RAPID_GOSSIP_SYNC_SERVER_DB_USER=lightning-rgs
      - RAPID_GOSSIP_SYNC_SERVER_DB_PASSWORD=docker
      - RAPID_GOSSIP_SYNC_SERVER_DB_NAME=ln_graph_sync
      - BITCOIN_REST_DOMAIN=bitcoin-core-tbtc
      - BITCOIN_REST_PORT=18332
      - BITCOIN_REST_PATH=/rest/
    command: 'cargo run'

  postgres:
    image: 'postgres:12-alpine'
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=lightning-rgs
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ln_graph_sync

  bitcoin-core-tbtc:
    container_name: bitcoin-core
    image: ruimarinho/bitcoin-core:alpine
    restart: always
    ports:
      - "0.0.0.0:18332:18332"
      - "0.0.0.0:18443:18443"
      - "0.0.0.0:18444:18444"
      - "0.0.0.0:18445:18445"
      - "0.0.0.0:28332:28332"
      - "0.0.0.0:28333:28333"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .bitcoin:/home/bitcoin/.bitcoin
    command:
      - "-printtoconsole"
      - "-testnet"
      - "-rpcallowip=0.0.0.0/0"
      - "-rpcbind=0.0.0.0"
      - "-rpcuser=vault"
      - "-rpcpassword=vault"
      - "-rpcport=18332"
      - "-zmqpubrawblock=tcp://0.0.0.0:28332"
      - "-zmqpubrawtx=tcp://0.0.0.0:28333"
      - "-rest"

volumes:
  postgres: null
